### PR TITLE
Added loadout: US_USMC_2010_wdl/des

### PR DESCRIPTION
**Pull request by AChesheireCat**
Added both woodland and desert versions.

### CODE REVIEW

**Comment by Freddo3000** [comment]
Won't review until conflicts are resolved.

**Comment by AChesheireCat** [comment]
I have no clue how to resolve this problem at this time. It doesn't seem to like the submission regardless of what fix I try to implement.

**Comment by Freddo3000** [comment]
@AChesheireCat TS and I'll show you ho

**Comment by AChesheireCat** [comment]
Resubmitting because I think I have an idea on how to fix this.

**Pull request closed without merging**
