### PR TITLE
Added "TVT Ready" loadout category

### PR DESCRIPTION
**Pull request by leotht**
Loadouts have reduced ordnance and are generally balanced with each other, within their specific quirks and limitations.

Started with a few to check if it's working and if it's viable, will continue working on it in my free time.

### CODE REVIEW

**Review by BorderKeeper — APPROVED** [review]
lgtm it's good to have this distinction so people know it's tvt compatible

**Comment by Freddo3000** [comment]
Pretty sure it is standard to have 1 frag per player in TVTs, most of these loadouts appear to have 2 frags per player.

**Comment by leotht** [comment]
Seems like I forgot to reduce frags for one of the German ones. SMG still has two grenades as means to compensate for their limited effectiveness.

**Comment by Freddo3000** [comment]
Yeah now when you point it out that seems to be the case.

**Pull request merged**
