### PR TITLE
Update macros.inc

### PR DESCRIPTION
**Pull request by hazardouschurch**
Suggested changes to rifleman loadouts. I have not had time to test loadouts. @Freddo3000 @AChesheireCat

### CODE REVIEW

**Review by Freddo3000 — CHANGES_REQUESTED** [review]
I'm not really against it, however I'd like to avoid putting it in the medical macro.

**Comment by AChesheireCat** [comment]
Concur with Freddo, recommend adding a rifleman_utility macro instead of stuffing it into the medical macro. This will also allow loadout makers to decide if they want the extra equipment in their loadouts or not.

**Comment by hazardouschurch** [comment]
Its all a matter of time. Either we rename the medical to just gear or we make another macro. Both would require changing all of the loadouts adding one line of code. Unless you have another easier way your getting stuck on the naming scheme for something that one line of code will do. If people want custom load outs they will make there own and can write there own macros its not that hard.

**Comment by AChesheireCat** [comment]
I think you've got good points, I just think that it'd be a better idea if we were to keep clearly defined macros ala medical_r vs. FAC. While it'll force the need to update the old loadouts (I think they're due for updates anyways) it'll keep the macros clearly defined as well as give loadout makers more options in terms of custom loadouts (removal of extraneous clutter for focused loadouts).

I also support adding colored paint cans to loadouts :)

**Comment by Freddo3000** [comment]
> I also support adding colored paint cans to loadouts :)

👎

**Comment by hazardouschurch** [comment]
After i wrote that  and thought about it for a minute its really only like what 50 files. It not terrible i was still thinking of the old arcore way with individual files which would have been like 3000+ files. I would like to see E-tools be added as well. I feel maybe having two macros for a under equipped and a full equipped force could be useful as i doubt a rebel would carry zip ties and spray paint.

**Comment by AChesheireCat** [comment]
Agreed - maybe a tiered macro that goes "utility_limited" and has only an e-tool and handcuffs and then another that is "utility_expanded" that has paint, etc. etc. and where "utility_expanded" inherits from "utility_limited"? Just spitballing here.

**Comment by AChesheireCat** [comment]
ie.)

#define UTILITY_LIM \
"ACE_EntrenchingTool", \
"whatevertheclassnameforziptiesis" \

#define UTILITY_EXP \
"ACE_EntrenchingTool", \
"whatevertheclassnameforziptiesis" \
"ACE_IR_Strobe_Item", \
"ACE_Flashlight_XL50", \
"ACE_microDAGR"

**Comment by Freddo3000** [comment]
I'm not a fan of this idea, and think it should probably be more left to a per-loadout basis. What logic is there in giving a high-speed, low-drag loadout a entrenching tool? What if I want to give my Russian loadout a KSF-1 instead of a XL50? Just to name a couple of examples.

Zipties are about as far as I'd like to push it, as it is a very small item that has a fair amount of usage.

**Pull request closed without merging**
