### PR TITLE
Add OFrP Magazine Compatibility

### PR DESCRIPTION
**Pull request by Drofseh**
Add OFrP magazines to CBA magwells and add the magwells to OFrP weapons

To Do:
- [x] Add AANF1 compatibilty

### CODE REVIEW

**Review by puzzleddev — COMMENTED** [review]
Are the changes to indentation style intentional? If so, what is the reason?

**Comment by Drofseh** [comment]
> Are the changes to indentation style intentional? If so, what is the reason?

My IDE automatically changes tabs to spaces

**Comment by Freddo3000** [comment]
> > Are the changes to indentation style intentional? If so, what is the reason?
> 
> My IDE automatically changes tabs to spaces

Make sure to configure it to use the https://github.com/ARCOMM/arc_misc/blob/master/.editorconfig, unless you want to change indentation everywhere.

**Comment by Drofseh** [comment]
> > > Are the changes to indentation style intentional? If so, what is the reason?
> > 
> > 
> > My IDE automatically changes tabs to spaces
> 
> Make sure to configure it to use the https://github.com/ARCOMM/arc_misc/blob/master/.editorconfig, unless you want to change indentation everywhere.

I'm currently set up to follow ACE's standards.

**Comment by Freddo3000** [comment]
If you want to update the indentation of the project, go ahead but I'd avoid having mixed indentation standards.

**Comment by Drofseh** [comment]
> If you want to update the indentation of the project, go ahead but I'd avoid having mixed indentation standards.

Sure I can do that in a separate PR

**Comment by Drofseh** [comment]
moved to https://github.com/ARCOMM/arc_config/pull/4

**Pull request closed without merging**
